### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by andersfylling** [hbollon/go-edlib#1]
Hi, it would be great to see benchmarks between the algorithms. Creating a graph and putting them in the README, would be really nice =)

**Comment by hbollon** [comment]
Great idea, I will try to do that in the week! 😄

**Comment by hbollon** [comment]
http://benchgraph.codingberg.com/q3

Is it ok? If you notice any missing cases which could be interesting or on the contrary some useless ones, let me know! :+1: 
I will update the Readme with that and push the benchmark package on the main branch soon :smile:

**Comment by andersfylling** [comment]
Hi, that was quick!

I would consider using bars instead, as the benchmarks are unrelated =) But it's nice to see!

**Comment by hbollon** [comment]
I will see to change the graph type but the program I use to convert the output directly from the go test output ([BenchGraph](https://github.com/codingberg/benchgraph)) don't have any option built-in to change that.

For the raw benchmark output, it's planned :wink:. In the _tests_ folder, I will push the go file for generate benchmarks, a bash script to allow users to launch it and the output file that I had generated with this graph.

**Comment by hbollon** [comment]
So, I have pushed all of that on master :smile:, including:
- Benchmark graph located in the ReadMe (still represented with curves for the moment, I will try to make it more ergonomic and readable in the future)
- Raw output bench file located in **./tests/outputs** sub-directory, it contains memory allocations data and sim/err print for each cases
- A bash script used to easily generate benchmarks located in **./tests** sub-directory
