### ISSUE TITLE
Missing methods for string shingling

### ISSUE THREAD

**Issue by ShriprajwalK** [hbollon/go-edlib#10]
Missing methods for string shingling(https://en.wikipedia.org/wiki/W-shingling) aka n-grams for strings. In general, Cosine similarity and Jaccard index, among other methods, are computed on n-grams of the string, instead of the string itself(eg: https://www.joyofdata.de/blog/comparison-of-string-distance-algorithms/). Right now, we just split the string on spaces and compute the index based on the words in the string, which is fine but is probably not technically correct. 
I propose we introduce a method to shingle the given strings so that we can later use the shingled string in finding cosine similarity, etc. This has been done before here:
Java: https://github.com/tdebatty/java-string-similarity
Julia: https://github.com/matthieugomez/StringDistances.jl

I think we should introduce a function that does something like:
```
// Function signature
shingle(str string, n int) map[string]int
// Example usage:
shingled_s1 := shingle("ABCD", 2) // returns map[AB:1 BC:1 CD:1]
shingled_s2 := shingle("ABCE", 2) // returns map[AB:1 BC:1 CE:1]
```
This will enable us to use these maps to later compute stuff, eg:
```
res := JaccardSimilarityWithShingles(shingled_s1, shingled_s2) // should return 0.5.
```

**Comment by ShriprajwalK** [comment]
If it's okay to add string shingling, I can create a PR for it

**Comment by hbollon** [comment]
Hey!
Great idea! If I understand well, with a n-grams decomposition of the input strings it will allow cosine/jaccard algorithms to be also adapted for words and no longer just sentences, right? (in addition of others benefits)
Of course if you're ready to provide a new PR it is with pleasure! 😄

**Comment by ShriprajwalK** [comment]
Yup exactly! I'll create a PR for it soon

**Comment by hbollon** [comment]
Hi @ShriprajwalK !
Any update about this ? :smile:
