### ISSUE TITLE
Q-gram index and Sorensen-Dice coefficient

### ISSUE THREAD

**Issue by ShriprajwalK** [hbollon/go-edlib#13]
Currently, we do not have methods for Q-gram and Sorensen-Dice coefficient(https://en.wikipedia.org/wiki/Sørensen–Dice_coefficient) which are fairly simple to implement since they're based on n-grams.

**Comment by ShriprajwalK** [comment]
If it's okay to add these, I can create a PR for it soon.

**Comment by hbollon** [comment]
Indeed that would be a great idea! I will greatly appreciate a PR :smile: 
I can help if needed
