### ISSUE TITLE
Reduce OSADamerau–Levenshtein space complexity from O(m*n) to O(3 * min(m,n))

### ISSUE THREAD

**Issue by tang-hi** [hbollon/go-edlib#16]
### Discussed in https://github.com/hbollon/go-edlib/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **tang-hi** July  2, 2022</sup>
When we calculate the distance of OSADamerau–Levenshtein, we actually calculate the matrix with dimension(m*n)
Suppose we have a matrix looks like

![1656691342850](https://user-images.githubusercontent.com/72755185/176930119-3b17a69c-daa6-45cd-9fe9-7856317b321d.jpg)
the value in (3,0) is always 3
the value in (3,1) depends on (3,0) (2,0) (2,1)
the value in (3,2) depends on (3,1) (2,1) (2,2) and (1,1)
we can found that the value in (row : i) only depends values in (row:i-1,i-2)
eg. the value in (row : 3) only depends values in (row:2,1)

So any row number >= 3, we could write it in (row %3, j),
eg. 
write the value of (3,0)  in (0,0)  .... (3,j) in (0,j)
write the value of (4,0)  in (1,0)  .... (4,j) in (1,j)
write the value of (i,0)  in (i%3,0)  .... (i,j) in (i%3,j)

In this way, we only need the matrix with dimension(3, min(m,n)) to calculate OSADamerau–Levenshtein distance 
Here is the [code](https://github.com/tang-hi/fuzzysearch/blob/Damerau%E2%80%93Levenshteinu/fuzzy/levenshtein.go) to illustrate my idea</div>

**Comment by hbollon** [comment]
Your PR was merged 🥳 
Thanks again for your contribution and all that informations about it!
I will dig a little bit more into your improvement and make some additional tests and documentation updates before releasing a new tag. I will try to do that in the week. (I keep the associated discussion open in case I have questions 😉)
