### ISSUE TITLE
LCSDiff prints himself to stdout & Unicode issues with LCS functions

### ISSUE THREAD

**Issue by aloska** [hbollon/go-edlib#4]
Maybe you forgot to delete after debugging:

fmt.Printf("%v\n", diff)

And... thanks for your working on all of this

**Comment by hbollon** [comment]
Hey! 
Thanks a lot for this find! This print escaped me :smile: 
It's now fixed on main branch

**Comment by aloska** [comment]
Thanks, and 1 more please))
I see the LCSBacktrack doesn't work with unicode. I think this is because 
`return processLCSBacktrack(str1, str2, lcsProcess(runeStr1, runeStr2), len(str1), len(str2)), nil`
len(str1) and len(str2) are not same with len(runeStr1) and len(runeStr2)
And maybe there should be len(runeStr1) and len(runeStr2)?

**Comment by hbollon** [comment]
Arf, this is more annoying...
I will look after that.

**Comment by aloska** [comment]
yes, it works with  `len(runeStr1), len(runeStr2)`
if use in processLCSBacktrack function:
`...+ string(runeStr1[m-1])` instead `...+ string(str1[m-1])`

**Comment by hbollon** [comment]
It's fixed !
I also fixed the LCSDiff for unicode inputs and added unicode test cases for lcs functions.
Thanks for your help ! :smiley: 
Something else? Or can I close this issue? :smile:

**Comment by aloska** [comment]
hmm, I see your code fine now, but have panic;
[Playground](https://play.golang.org/p/gQrN7qq0tcc)
Maybe playground uses old module?

**Comment by aloska** [comment]
Yes, it works!
I just copied functions to playground - and all OK:
 [playground](https://play.golang.org/p/Mo_AALfsR8N)
Maybe some cash in playground should be refresh.

Thanks a lot!
