### ISSUE TITLE
LCSBacktrackAll not work

### ISSUE THREAD

**Issue by djsousuo** [hbollon/go-edlib#5]
My code:

`	ress,err:=edlib.LCSBacktrackAll(" 是ab是cde22f123g", "222222是ab是cd123")
	if err!=nil{
		fmt.Println(err)
	}else {
		fmt.Printf("%s", strings.Join(ress, "\r\n"))
	}
`

Shoud be print 
`
是ab是cd

123
`

But is print 
`
是ab是cd123
`

**Comment by hbollon** [comment]
Hi! 
Thanks for the issue, I will investigate

**Comment by hbollon** [comment]
Ok so I checked and it seems normal to me. 
" 是ab是cde22f123g" and  "222222是ab是cd123" have only one lcs and it's "是ab是cd123".
So LCSBacktrackAll return to you a slice with only one element:  "是ab是cd123". :smile:

**Comment by djsousuo** [comment]
Thank you for your reply
