### ISSUE TITLE
StringsSimilarity is broken for unicode

### ISSUE THREAD

**Issue by burkostya** [hbollon/go-edlib#7]
The test is failing

```go
func TestStringsSimilarity(t *testing.T) {
	str1 := "abcde"
	str2 := "бвгдж"
	str3 := "fghjk"
	sim12, _ := edlib.StringsSimilarity(str1, str2, edlib.Levenshtein)
	sim13, _ := edlib.StringsSimilarity(str1, str3, edlib.Levenshtein)
	if sim12 != sim13 {
		t.Errorf("different similarities, %v != %v", sim12, sim13)
	}
}
```

output: `different similarities, 0.5 != 0`

Similarity between "abcde" and "бвгдж" should be the same as between "abcde" and "fghjk".
Looks like bug in the `matchingIndex()` because it compares length of strings but `...Distance()` functions use runes.

**Comment by hbollon** [comment]
Hey @burkostya 
Thanks a lot for your issue, it's now fixed and I created a new release [v1.3.4](https://github.com/hbollon/go-edlib/releases/tag/v1.3.4) for this :smile:
