### ISSUE TITLE
Jaccard Similarity missing

### ISSUE THREAD

**Issue by ShriprajwalK** [hbollon/go-edlib#8]
Jaccard similarity coefficient(https://en.wikipedia.org/wiki/Jaccard_index) is a simple way to measure string similarity. I cannot find a function implementing this, is there one? If it is isn't there yet, it can be easily implemented using existing functions from cosine.go

**Comment by ShriprajwalK** [comment]
If it's okay to add the Jaccard index, I can create a PR for it

**Comment by hbollon** [comment]
Hi! 
A PR for that will be welcome! :smile: 
It will just have to respect a few constraints:
- The algorithm must be compatible with Unicode 
- It must be test  covered with all possibles cases:
  -  With ASCII words
  -  With multiples ASCII words
  -  With Unicode words
  -  Cases which will triggering possibles errors if there is any (like with Hamming and words with different length)

I can't wait to see your feature! If you need help ping me here or in a PR :wink:
